DISCORD_TOKEN = 'YOURS_DISCORD_TOKEN'
DATABASE_URL = 'DATABASE_URL'

## Discord IDs
REVIVE_CHANNEL = "CHANNEL_ID" # Channel ID where requests for revies will be sent
REVIVE_ROLE = "ROLE_ID" # Role ID that will be mentioned when a revive request is sent
REVIVE_FACTION_GUILD_ID = "GUILD_ID" # Guild ID of the reviving faction, this unlocks some additional features
OWNER_ID = "USER_ID" # Discord ID of the bot owner
ADMINS = "USER_ID" # List of Discord IDs that are considered admins (They get to create contracts and such)


REVIVE_FACTION = "TORN_FACTION_ID" # Faction ID that will be mentioned when a revive request is sent
REVIVE_FACTION_API_KEY = "TORN_API_KEY" # API key that has faction access

TEST_API_KEY= "TORN_API_KEY" # For testing purposes, will / should only be used when running in dev mode
DEV = "true" # true for Secrets.dev.toml, false for Secrets.toml way to have dev and production running on the same codebase


